main project
      7.1       : AquaCrop Version (August 2023)
      1         : Year number of cultivation (Seeding/planting year)
  45292         : First day of simulation period - 1 January 2025   
  45401         : Last day of simulation period - 20 April 2025    
  45292         : First day of cropping period - 1 January 2025   
  45401         : Last day of cropping period - 20 April 2025    
-- 1. Climate (CLI) file
   ZRavena.CLI
   C:\Users\hudso\Desktop\testes\data\
   1.1 Temperature (Tnx or TMP) file
   ZRavenaTemp.Tnx
   C:\Users\hudso\Desktop\testes\data\
   1.2 Reference ET (ETo) file
   ZRavenaETo.ETo
   C:\Users\hudso\Desktop\testes\data\
   1.3 Rain (PLU) file
   (None)
   (None)
   1.4 Atmospheric CO2 concentration (CO2) file
   MaunaLoa.CO2
   C:\Users\hudso\Desktop\testes\data\
-- 2. Calendar (CAL) file
   (None)
   (None)
-- 3. Crop (CRO) file
   ZLettuce.CRO
   C:\Users\hudso\Desktop\testes\data\
-- 4. Irrigation management (IRR) file
   teste.IRR
   C:\Users\hudso\Desktop\testes\data\
-- 5. Field management (MAN) file
   ZCanteiroRavena.MAN
   C:\Users\hudso\Desktop\testes\data\
-- 6. Soil profile (SOL) file
   ZSoloRavena.SOL
   C:\Users\hudso\Desktop\testes\data\
-- 7. Groundwater table (GWT) file
   (None)
   (None)
-- 8. Initial conditions (SW0) file
   Zstart.SW0
   C:\Users\hudso\Desktop\testes\data\
-- 9. Off-season conditions (OFF) file
   (None)
   (None)
-- 10. Field data (OBS) file
   (None)
   (None)
